groups:
  - name: sec-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(error_rate_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: 'High error rate detected'
          description: 'Error rate is {{  }} which is above threshold of 0.1'

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(api_response_time_seconds_bucket[5m])) > 2.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High API response time'
          description: '95th percentile response time is {{  }}s which is above threshold of 2.0s'

      - alert: LowCacheHitRate
        expr: cache_hit_rate < 70
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'Low cache hit rate'
          description: 'Cache hit rate is {{  }}% which is below threshold of 70%'

      - alert: HighMemoryUsage
        expr: memory_usage_bytes / 1024 / 1024 / 1024 > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High memory usage'
          description: 'Memory usage is {{  }}GB which is above threshold of 1.5GB'

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Service is down'
          description: 'Service {{ .job }} has been down for more than 1 minute'
